# Generated by Django 5.2.12 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0002_video_processing_done_video_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]

