"""Signal handlers for video processing workflow."""

from django.db.models.signals import post_save
from django.dispatch import receiver

from .models import Video


@receiver(post_save, sender=Video)
def trigger_video_processing(sender, instance: Video, created: bool, **kwargs) -> None:
    """Enqueue video processing right after upload."""
    if not created or not instance.video_file or instance.processing_done:
        return
    from .tasks import process_video
    process_video.delay(instance.id)


@receiver(post_save, sender=Video)
def regenerate_thumbnail_when_removed(sender, instance: Video, created: bool, **kwargs) -> None:
    """Recreate autogenerated thumbnails when removed in admin."""
    if created or not instance.video_file or instance.thumbnail:
        return
    from .tasks import ensure_thumbnail
    ensure_thumbnail.delay(instance.id)

